name: iglu_ory_kratos_example
description: IGLU Ory Kratos Example
homepage: https://github.com/IGLU-Agency/iglu-ory-kratos-example
version: 0.2.0
environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  intl: ^0.17.0
  kratos_api_dart: ^1.0.0
  provider: ^6.0.2
  string_validator: ^0.3.0
  tuple: ^2.0.0

dev_dependencies:
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/kratos/
